library(ggplot2)
library(lattice)
library(png)
library(grid)

# Producing session-info.txt
sink("../../session-info.txt")
cat("\n")
cat("Software Programs and Versions:")
cat("\n")
cat("OS Mac Sierra")
cat("\n")
cat("R version 3.3.1")
cat("\n")
cat("Rstudio Version 0.99.893")
cat("\n")
cat("Pandoc")
cat("\n")
cat("Lyx")
cat("\n")
cat("Git")
cat("\n")

cat("\n")
cat("Packages Used:")
cat("\n")
cat("ggplot2, lattice, png, grid")
cat("\n")
sink()

